# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
