# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0005_auto_20180306_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', models.ImageField(upload_to='profile/')),
                ('user_name', models.CharField(max_length=30)),
                ('user_bio', models.CharField(max_length=250)),
            ],
        ),
    ]
