# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0010_auto_20180308_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['bio']},
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
