# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0012_auto_20180309_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to='image/'),
        ),
    ]
